---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: records.disco.stable.sap.cc
spec:
  group: disco.stable.sap.cc
  names:
    kind: Record
    plural: records
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: ""
      specReplicasPath: ""
      statusReplicasPath: ""
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata: {}
        spec:
          description: DiscoRecordSpec is the spec for a DiscoRecord resource
          properties:
            description:
              type: string
            hosts:
              items:
                type: string
              type: array
            record:
              type: string
            type:
              type: string
            zoneName:
              type: string
          required:
          - type
          - hosts
          - record
          type: object
        status:
          description: DiscoRecordStatus is the status for a DiscoRecord resource
          properties:
            recordsetStatus:
              type: string
          required:
          - recordsetStatus
          type: object
      type: object
  version: v1
