[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0-beta.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.6.2"

[[constraint]]
  name = "github.com/sapcc/go-vice"
  revision = "e4ca123d1d421af0bda4827071f7f7c42dc40aa0"

[prune]
  go-tests = true
  unused-packages = true
